### ISSUE TITLE
f-string expression part cannot include a backslash

### ISSUE THREAD

**Issue by cardenluo** [christian-byrne/python-interpreter-node#1]
F:\ComfyUI_Windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-05-19 12:03:06.306147
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: F:\ComfyUI_Windows_portable\python_embeded\python.exe
** Log path: F:\ComfyUI_Windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: F:\ComfyUI_Windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   1.0 seconds: F:\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 65384 MB
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
'pip' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Using device: cuda
Patching UNetModel.forward
UNetModel.forward has been successfully patched.
[Inspire Pack] Failed to load 'prompt-builder.yaml'
[ComfyUI-0️⃣ 2️⃣ 4️⃣ 6️⃣ ] Loaded all nodes and apis.
Comfy-Easy-Use v1.1.7: Loaded
Comfyui-ergouzi-DGNJD:解锁更多宝贵时光，去做更有意义的事情，这才是AI--------B站@灵仙儿和二狗子
### Loading: ComfyUI-Impact-Pack (Subpack: V0.5)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V0.69.2)
Total VRAM 24576 MB, total RAM 65384 MB
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
### ComfyUI Revision: 2166 [c3341228] | Released on '2024-05-07'
#fix sys.stdout.isatty
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
--------------
 ### Mixlab Nodes: Loaded
LaMaInpainting.available True
ClipInterrogator.available True
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
 --------------
------------------------------------------
### N-Suite Revision: 0
Current version of packaging: 23.2
Version of cpuinfo: Not found
Current version of git: 3.1.42
Current version of moviepy: 0.2.3.2
Current version of cv2: 4.9.0
Current version of skbuild: 0.17.6
Version of typing: Not found
Current version of diskcache: 5.6.3
Current version of llama_cpp: 0.2.26+cu121
Current version of timm: 0.9.16
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
Workspace manager - Openning file hash dict
### Loading: Workspace Manager (V1.0.0)
[05/19/24 12:04:39] WARNING  Your inference package version 0.9.13 is out of date! Please upgrade to      __init__.py:35
                             version 0.10.0 of inference for the latest features and bug fixes by running
                             `pip install --upgrade inference`.
SupervisionWarnings: BoxAnnotator is deprecated: `BoxAnnotator` is deprecated and will be removed in `supervision-0.22.0`. Use `BoundingBoxAnnotator` and `LabelAnnotator` instead

------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: F:\ComfyUI_Windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
FizzleDorf Custom Nodes: Loaded
# 😺dzNodes: LayerStyle -> Warning: F:\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Find 1 LUTs in F:\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\lut
# 😺dzNodes: LayerStyle -> Find 1 Fonts in F:\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\font
[tinyterraNodes] Loaded
[comfy_mtb] | INFO -> loaded 76 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
None
Please 'pip install apex'
Traceback (most recent call last):
  File "F:\ComfyUI_Windows_portable\ComfyUI\nodes.py", line 1876, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_Windows_portable\ComfyUI\custom_nodes\python-interpreter-node\__init__.py", line 2, in <module>
    from .python_interpreter_node import PythonInterpreter
  File "F:\ComfyUI_Windows_portable\ComfyUI\custom_nodes\python-interpreter-node\python_interpreter_node.py", line 220
    stdout_display = f"{f.getvalue()}\n{err.getvalue()}\n{'\n'.join(error_messages)}"
                                                                                     ^
SyntaxError: f-string expression part cannot include a backslash

Cannot import F:\ComfyUI_Windows_portable\ComfyUI\custom_nodes\python-interpreter-node module for custom nodes: f-string expression part cannot include a backslash (python_interpreter_node.py, line 220)

[rgthree] Loaded 38 exciting nodes.
[rgthree] Will use rgthree's optimized recursive execution.

**Comment by christian-byrne** [comment]
Fixed in Commit 9b93b7d which adds a stdout/stderr stream wrapper. Thank you for bringing this issue up. The node should be usable again. More improvements to come and feedback is always appreciated.
