### ISSUE TITLE
add to comfy-manager

### ISSUE THREAD

**Issue by drmbt** [christian-byrne/python-interpreter-node#5]
i transfer snapshots between environments a lot, and it would be a swell addition to the comfy ecosystem if this were available via the manager

**Comment by christian-byrne** [comment]
Thanks. I just updated the README with instructions for downloading via the manager:


> [!TIP]
>  To install via manager, you must first open the ComfyUI Manager settings and set the `channel` setting to `dev`:
>
>
> <details>
>
> <summary> &nbsp; See Picture of Specified Setting </summary>
> 
> ![](wiki/comfyui-manager-setting.png)
>
> </details>
>
